"""Added resume_file column to Job

Revision ID: eb4598cc4e15
Revises: 3b639069c410
Create Date: 2025-11-13 07:25:06.737855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4598cc4e15'
down_revision = '3b639069c410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.drop_column('resume_file')

    # ### end Alembic commands ###
